FROM python:3.9-slim

# curl is required for health check, not for the app itself
RUN apt-get update && apt-get install -y curl

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

CMD ["fastapi", "run", "app/main.py", "--port", "8008"]
