# k8s/db-init-scripts.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-scripts
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS test_table (
        id SERIAL PRIMARY KEY,
        name VARCHAR(50)
    );

    INSERT INTO test_table (name) VALUES ('Test Record');
