apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: {{ .Values.fastapi.replicas }}
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: {{ .Values.fastapi.image }}
        ports:
        - containerPort: 8008
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.fastapi.env.POSTGRES_HOST }}
        - name: POSTGRES_DB
          value: {{ .Values.fastapi.env.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .Values.fastapi.env.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.fastapi.env.POSTGRES_PASSWORD }}