apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: {{ .Values.fastapi.service.type }}
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    port: {{ .Values.fastapi.service.port }}
    targetPort: 8008